.github/workflows/python_e2e_test.yml
python/.env.example
python/README.md
python/cdp/cdp_client.py
python/changelog.d/30.feature.md

This PR is a fast follow fix for a change made in #30. The client config now accepts `CDP_API_KEY_ID` (in addition to `CDP_API_KEY_NAME` for backwards compat).

chore(python): use CDP_API_KEY_ID

---

.github/workflows/typescript_e2e_test.yml
typescript/.changeset/spicy-bananas-travel.md
typescript/.env.example
typescript/README.md
typescript/src/client/cdp.ts

#29 should have made this change to use `CDP_API_KEY_ID` instead of `CDP_API_KEY_NAME`. It's being added as an option for devs, while keeping `CDP_API_KEY_NAME` as a fallback value for backwards compat.

fix(typescript): accept CDP_API_KEY_ID over CDP_API_KEY_NAME

---

python/cdp/analytics.py
python/cdp/cdp_client.py
python/cdp/test/test_analytics.py
python/changelog.d/56.misc.md
typescript/.changeset/clean-ideas-hug.md
typescript/src/analytics.test.ts
typescript/src/analytics.ts
typescript/src/auth/hooks/axios/withAuth.ts
typescript/src/client/cdp.test.ts
typescript/src/client/cdp.ts
typescript/src/e2e.test.ts
typescript/src/openapi-client/cdpApiClient.test.ts
typescript/src/openapi-client/cdpApiClient.ts
typescript/src/openapi-client/errors.ts

This PR adds a client service API key so that we can view error events in Amplitude.
It also expands on the axios error log to include the `error.cause` property in order to capture more information when unexpected errors occur.
Tested a few scenarios locally.
**Normal API Error**
```
APIError: EVM account with the given name already exists.
at cdpApiClient (/Users/ryan/code/public/cdp-sdk/typescript/src/openapi-client/cdpApiClient.ts:137:15)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async EvmClient.createAccount (/Users/ryan/code/public/cdp-sdk/typescript/src/client/evm/evm.ts:79:21)
at async EvmClient.ClassToWrap.<computed> (/Users/ryan/code/public/cdp-sdk/typescript/src/analytics.ts:115:16)
at async main …
```

fix: improve error handling

---

examples/typescript/evm/getOrCreateAccount.ts
examples/typescript/solana/getOrCreateAccount.ts
typescript/.changeset/slow-meals-knock.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/client/solana/solana.test.ts
typescript/src/client/solana/solana.ts
typescript/src/client/solana/solana.types.ts
typescript/src/e2e.test.ts

Add `getOrCreateAccount` functions to both the evm and solana sdks to combine the account existence check with conditional account creation, for faster and better devx.
There was discussion around including an additional `created` bool field to the account to denote whether the account was created by the function, or whether it previously existed. However, on further thought, that field is omitted because it would likely cause more pain than not because it changes the structure returned to consumers who may be simply expecting the normal `Account` type. In the scenario devs really want it, they may just use the separate get and create functions Let me know if you still strongly believe we should add it.
Added unit tests and examples
A couple of things to include in your PR for …

feat(typescript): Add getOrCreateAccount for evm and solana

---

.github/workflows/deploy-gh-pages.yml
.github/workflows/typescript_publish.yml
RELEASE.md
typescript/.eslintrc.json
typescript/.npmrc
typescript/package.json
typescript/scripts/updateVersion.ts

This PR uses a feature freshly added to `changesets/action` which allows us to use the action while requiring and enforcing signed commits. The TypeScript release process is now fully automated, except for needing to post to Discord, which will also be automated soon.

chore(typescript): automate release process

---

examples/python/evm/account.sign_typed_data.py
examples/python/evm/sign_typed_data.py
python/cdp/evm_client.py
python/cdp/evm_message_types.py
python/cdp/evm_server_account.py
python/cdp/openapi_client/models/eip712_message.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py
python/cdp/test/test_evm_server_account.py
python/changelog.d/132.feature.md

With this PR, the cdp client and server accounts may now sign EIP-712 typed data.
For example:
```py
signature = await cdp.evm.sign_typed_data(
address=account.address
message=<eip-712-message>
)
```
or
```py
signature = await account.sign_typed_data(
message=<eip-712-message>
)
```
Added examples and unit tests.

feat(python) Add support for EIP-712 signing

---

python/pyproject.toml
python/uv.lock

Due to the amount of action providers in AgentKit, and the requirement in Python that only one version of each package be loaded into an environment, we're finding that the dependencies of `cdp-sdk` are slightly too strict.
This PR updates the ranges of 3 dependencies just enough that AgentKit will be able to properly use `cdp-sdk`
Untested beyond installing and building. This will get indirectly tested against the next AgentKit Python release that is in development, as I made these changes locally to build against.

depps: bumped dependencies for agentkit support

---

python/cdp/test/test_e2e.py
typescript/src/e2e.test.ts

This supports our E2E tests running with a specified E2E_BASE_PATH, or defaulting to the existing API path when omitted.
N/A

chore: Support E2E test with configure base path

---

typescript/.changeset/polite-owls-ask.md
typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts

Similar to what viem does: https://github.com/wevm/viem/blob/main/src/utils/signature/hashTypedData.ts#L53
This fixes an issue with x402 integrators where signTypedData without explicitly EIP712Domain would not work

fix(typescript): Fixed signTypedData to automatically infer EIP712Domain

---

typescript/.changeset/sweet-aliens-sin.md
typescript/src/openapi-client/cdpApiClient.test.ts
typescript/src/openapi-client/cdpApiClient.ts

Log response body in the `errorMessage` for unexpected non-OAPI error scenarios.
Before:
```
statusCode: 400,
errorType: 'unexpected_error',
errorMessage: 'An unexpected error occurred.',
correlationId: undefined,
errorLink: 'https://docs.cdp.coinbase.com/api-v2/docs/errors',
[cause]: undefined
```
After:
```
statusCode: 400,
errorType: 'unexpected_error',
errorMessage: 'An unexpected error occurred: "<html>\\r\\n<head><title>400 Request Header Or Cookie Too Large</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>Request Header Or Cookie Too Large</center>\\r\\n</body>\\r\\n</html>\\r\\n"',
correlationId: undefined,
errorLink: 'https://docs.cdp.coinbase.com/api-v2/docs/errors',
[cause]: undefined
```
A couple of things to include in your PR for …

fix(typescript): Log response body for unexpected non-OAPI error scenarios

---

typescript/src/e2e.test.ts

This updates the E2E tests to import with a different encryption key to suport testing against different environments.
* Updated E2E test

chore: Support importing with different encryption keys

---

examples/typescript/evm/scopedAccount.customNode.ts
typescript/.changeset/calm-impalas-rule.md
typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.test.ts
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.ts
typescript/src/accounts/evm/types.ts
typescript/src/e2e.test.ts

This PRs adds a managed requestFaucet, sendTransaction and waitForTransactionReceipt to EvmServerAccount.
Added e2e and unit tests, as well as a new example script showcasing the network scoping feature.

feat: implement send and wait functions on scoped evm server account

---

examples/python/evm/evm_local_account.py
python/cdp/evm_local_account.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_local_account.py
python/changelog.d/246.bugfix.md

Fixed EvmLocalAccount sign typed data compatibility with eth-account.
- Convert bytes32 to hex string to make it serializable
- Include EIP712 domain if missing from types
- Return SignedMessage
Updated unit and e2e tests, and updated examples.

fix(python): Update evm local account sign typed data

---

typescript/.changeset/soft-colts-fetch.md
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.ts

Currently seeing this error:
```
APIError: request body has an error: doesn't match schema: property "network" is missing
```
This is because the transfer method was not being set correctly.

fix: use correct transfer method in network scoped server account

---

examples/python/evm/smart_account.sign_typed_data.py
examples/typescript/evm/smartAccount.signTypedData.ts
python/cdp/evm_smart_account.py
python/cdp/network_config.py
python/cdp/test/test_evm_smart_account.py
python/changelog.d/284.feature.md
typescript/.changeset/gold-books-pay.md
typescript/src/accounts/evm/networkToChainResolver.test.ts
typescript/src/accounts/evm/networkToChainResolver.ts
typescript/src/accounts/evm/resolveViemClients.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/actions/evm/types.ts

Adds signTypedData to the EvmSmartAccount objects in both Python and TypeScript, leveraging the pre-existing smart account signTypedData util.
Tested with the new examples!

feat: add signTypedData on EvmSmartAccount

---

typescript/src/accounts/evm/resolveViemClients.ts
typescript/src/actions/evm/fund/fund.ts
typescript/src/actions/evm/fund/quoteFund.ts
typescript/src/analytics.ts
typescript/src/auth/utils/jwt.ts
typescript/src/client/evm/evm.ts
typescript/src/client/solana/solana.ts
typescript/src/errors.ts

This PR adds a UserInputValidationError which is filtered out at the analytics layer so that we do not send these types of errors to Amplitude.
Tested manually

chore(typescript): do not emit user input validation errors

---

python/cdp/api_clients.py
python/cdp/cdp_client.py
python/cdp/test/test_cdp_client.py
python/changelog.d/298.bugfix.md

This PR adds a runtime error to the Python SDK when a builder attempts to use the SDK when the client has been closed, either manually or outside of an async context.
Tested manually

fix: gracefully handle closed client

---

typescript/src/e2e.test.ts
typescript/src/openapi-client/errors.ts

add suite of typescript e2e tests for policy evaluation
test all major use cases

test(CDP-955): add typescript e2e tests for policy evaluation

---

examples/typescript/evm/createSpendPermission.ts
typescript/src/auth/utils/http.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/e2e.test.ts

This PR adds createSpendPermission which allows a smart account to create a spend permission for a designated spender account (EOA or smart account).

feat(CDPSDK-1238): add create spend permission

---

examples/typescript/pnpm-lock.yaml
typescript/pnpm-lock.yaml
typescript/src/openapi-client/cdpApiClient.test.ts
typescript/src/openapi-client/cdpApiClient.ts
typescript/src/package.json

This PR adds [axios-retry](https://www.npmjs.com/package/axios-retry) to automatically retry network errors and idempotent 5xx errors. We are using the default `retryCondition`, which is:
> A callback to further control if a request should be retried. By default, it retries if it is a network error or a 5xx error on an idempotent request (GET, HEAD, OPTIONS, PUT or DELETE).
Note: Python already implements a retry strategy: https://github.com/coinbase/cdp-sdk/blob/main/python/cdp/openapi_client/cdp_api_client.py#L44-L45

chore: add axios-retry

---

.github/workflows/typescript_publish.yml

We've set up NPM Trusted Publishing which uses an OIDC flow to request an auth token to publish, removing the need for us to persist an auth token to the repo.
This will be tested during our next publish. If the next publish fails, we can revert this PR to unblock; otherwise we're all good and would have validated that the Trusted Publishing setup is working correctly, and then we can apply it to other repos.

chore: use trusted publishing

---

python/cdp/test/test_e2e.py
typescript/src/e2e.test.ts

Add retries to known flaky e2e tests on TypeScript and Python, configurable with number of attempts and retry delay.
Updated e2e tests.

chore: Add retries to known flaky e2e tests

---

typescript/src/accounts/evm/resolveViemClients.test.ts

This will reduce flakiness in unit tests caused by using public RPC – the test now fully mocks the network so no real network requests are being made.

chore: properly mock out network requests in viem tests

---

typescript/src/e2e.test.ts
typescript/src/policies/solanaSchema.ts

- use a unique test account for policy evaluation tests to avoid failures from concurrent operations being evaluated against transient policies 

fix(CDPSDK-1317): e2e stability policy eval test causing flakiness

---

typescript/src/e2e.test.ts

This makes it so that we can conditionally skip EVM token balances e2e tests behind the env var flag `CDP_E2E_SKIP_EVM_TOKEN_BALANCES`.
This only impacts e2e tests

chore: Conditionally skip EVM token balances e2e tests

---

examples/python/uv.lock
python/cdp/actions/evm/transfer/account_transfer_strategy.py
python/cdp/actions/evm/transfer/smart_account_transfer_strategy.py
python/cdp/test/test_account_transfer_strategy.py
python/changelog.d/427.bugfix.md
typescript/.changeset/green-years-bake.md
typescript/src/actions/evm/transfer/accountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts

Removed the ERC20 approval step from token transfers for both EOAs and Smart Accounts.
The change affects both TypeScript and Python implementations, removing the redundant approval calls from:
- Account transfer strategy
- Smart account transfer strategy
Updated existing tests to reflect the removal of the approval step:
- Adjusted mock expectations to only expect a single transaction call
- Verified that transfer functionality continues to work correctly
- Updated assertions to check for a single transaction instead of two
Tested locally by running all transfer example scripts to completion.

fix: remove approal in transfer method
