coinbase/cdp-sdk

go/examples/example.go
typescript/src/client/cdp.ts
typescript/src/client/evm/evm.ts
typescript/src/client/solana/solana.ts
typescript/src/e2e.test.ts
typescript/src/examples/solana/listAccounts.ts

This PR:
* Completes JS docstrings
* Renames all references of `cdpClient` to `cdp`

chore: polish

---

.github/workflows/update_openapi.yml

See: https://github.com/peter-evans/create-pull-request/blob/271a8d0340265f705b14b6d32b9829c1cb33d45e/docs/concepts-guidelines.md#commit-signature-verification-for-bots

chore: update update_openapi.yml to use signed commits

---

README.md

This PR adds a Contributors section to the top-level README.md so we can highlight all of the community members that have contributed to CDP SDK!
No tests needed, just documentation changes!

docs: Add Contributors section to README.md

---

.github/workflows/go_lint.yml
.github/workflows/go_test.yml
.github/workflows/python_e2e_test.yml
.github/workflows/python_lint.yml
.github/workflows/python_test.yml
.github/workflows/typescript_e2e_test.yml
.github/workflows/typescript_lint.yml
.github/workflows/typescript_test.yml
.github/workflows/update_openapi.yml

This PR:
* Implements a [draft PR workaround](https://github.com/peter-evans/create-pull-request/blob/271a8d0340265f705b14b6d32b9829c1cb33d45e/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs) to ensure CI checks run on the auto-generated PRs. This works by 1. configuring the auto-gen PR to open in a Draft state, and 2. triggering CI checks on `ready_for_review`, so when a maintainer changes the PR state to Ready, the checks will run

chore: run checks on autogenerated openapi pr

---

python/README.md
typescript/README.md

chore: fix readme quickstarts

---

go/CHANGELOG.md
python/CHANGELOG.md
typescript/CHANGELOG.md

chore: changelog initial release

---

typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/client/evm/evm.ts
typescript/src/e2e.test.ts
typescript/src/examples/evm/sendTransaction.ts
typescript/src/examples/evm/signTransaction.ts

This removes the unnecessary zeroed-out signatures from our examples as our backend can handled RLP-encoded EIP-1559 transactions with or without the signature bytes.

chore: Remove unnecessary zeroed-out signatures

---

.github/workflows/typescript_publish.yml

chore: fix ts publish

---

typescript/package.json

This is required for provenance publishing

chore: add repo url to ts package.json

---

python/CHANGELOG.md
python/pyproject.toml
python/uv.lock

chore: bump cdp-sdk to 1.0.1

---

typescript/.changeset/witty-papers-flow.md
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/types.ts
typescript/src/e2e.test.ts
typescript/src/examples/evm/sendTransaction.ts

This came out of confusion around using Viem to send transaction, as well as a bug in the [Transfer funds quickstart](https://docs.cdp.coinbase.com/wallet-api-v2/docs/quickstart#transfer-funds)
Tested the `sendTransaction` example works.
```
pnpm tsx src/examples/evm/sendTransaction.ts 
Successfully created EVM account: 0x69cD12eB73ed7ddeC5949fDCC719C1b883c0185D
Successfully requested ETH from faucet: 0x9c866065570393e15b06a4b36c0589dedcba7f4b1673885bda1db0c6537aa28d
Waiting for faucet funds...
Faucet transaction confirmed
Transaction explorer link: https://sepolia.basescan.org/tx/0x7372155a86952bcdc61afedf5e342e94e39b48d53aec16eda84bbd44b4d9379b
```

fix: use TransactionSerializable to improve compatability with toAccount

---

typescript/.changeset/witty-papers-flow.md
typescript/CHANGELOG.md
typescript/package.json

chore 1.0.1 @coinbase/cdp-sdk

---

python/cdp/examples/README.md
python/cdp/examples/evm/create_account.py
python/cdp/examples/evm/create_account_idempotency.py
python/cdp/examples/evm/create_server_smart_wallet_and_send.py
python/cdp/examples/evm/create_smart_wallet_and_send.py
python/cdp/examples/evm/send_transaction.py
python/cdp/examples/solana/create_account.py
python/cdp/examples/solana/send_transaction.py

Moves all Python examples into their corresponding subfolders

chore: organize python examples

---

RELEASE.md

chore: update RELEASE.md

---

typescript/.changeset/nice-clubs-visit.md
typescript/package.json
typescript/src/auth/README.md

This PR exports the auth subpackage, and updates the auth/README.md. This was tested in a standalone project importing the locally built package and running the code from the README
Running this code:
```ts
import {
generateJwt,
getAuthHeaders,
axiosHooks,
} from "@coinbase/cdp-sdk/auth";
import axios from "axios";
const apiKeyId = "...";
const apiKeySecret = "...";
const walletSecret = "...";
async function main() {
// const evmAccount = await cdp.evm.createAccount();
// console.log("Created account with address", evmAccount.address);
const jwt = await generateJwt({
apiKeyId: apiKeyId,
apiKeySecret: apiKeySecret,
requestMethod: "GET",
requestHost: "api.cdp.coinbase.com",
requestPath: "/platform/v2/evm/accounts",
expiresIn: 120, // optional (defaults to 120 seconds)
});
console.log(jwt); …
```

feat: export auth subpackage

---

python/cdp/auth/README.md

The README was referencing v1 endpoints. This PR updates it to reference v2 endpoints

chore(python): fix auth readme

---

.github/workflows/typescript_e2e_test.yml
typescript/.changeset/eager-days-kiss.md
typescript/README.md
typescript/src/auth/utils/http.ts
typescript/src/client/cdp.ts
typescript/src/e2e.test.ts
typescript/src/examples/evm/createAccount.ts
typescript/src/examples/evm/createSmartAccount.ts
typescript/src/examples/evm/getAccount.ts
typescript/src/examples/evm/getSmartAccount.ts
typescript/src/examples/evm/getUserOperation.ts
typescript/src/examples/evm/listAccounts.ts
typescript/src/examples/evm/listSmartAccounts.ts
typescript/src/examples/evm/prepareUserOperation.ts
typescript/src/examples/evm/requestFaucet.ts
typescript/src/examples/evm/sendTransaction.ts
typescript/src/examples/evm/sendUserOperation.ts
typescript/src/examples/evm/signHash.ts
typescript/src/examples/evm/signMessage.ts
typescript/src/examples/evm/signTransaction.ts
typescript/src/examples/evm/waitForUserOperation.ts
typescript/src/examples/solana/createAccount.ts
typescript/src/examples/solana/getAccount.ts
typescript/src/examples/solana/listAccounts.ts
typescript/src/examples/solana/requestFaucet.ts
typescript/src/examples/solana/signAndSendTransaction.ts
typescript/src/examples/solana/signAndSendVersionedTransaction.ts
typescript/src/examples/solana/signMessage.ts
typescript/src/examples/solana/signTransaction.ts

This PR:
* Adds support for configuring `CdpClient` without manually passing the config options
* Improves error message when missing Wallet Secret
* Updates examples to use this new config method
This is the error that is printed when the api key id or secret is not set:
```
Error: 
Missing required CDP Secret API Key configuration parameters.
You can set them as environment variables:
CDP_API_KEY_ID=your-api-key-id
CDP_API_KEY_SECRET=your-api-key-secret
You can also pass them as options to the constructor:
const cdp = new CdpClient({
apiKeyId: "your-api-key-id",
apiKeySecret: "your-api-key-secret",
});
If you're performing write operations, make sure to also set your wallet secret:
CDP_WALLET_SECRET=your-wallet-secret
This is also available as an option to the constructor:
const cdp = …
```

feat(typescript): add support for client config via env vars

---

typescript/.changeset/spicy-bananas-travel.md
typescript/CHANGELOG.md
typescript/package.json

chore: bump @coinbase/cdp-sdk to 1.1.1

---

python/cdp/cdp_client.py

Closes https://github.com/coinbase/cdp-sdk/issues/39

chore: fix typo

---

typescript/.changeset/bright-bananas-move.md
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/e2e.test.ts

The `getUserOperation` wrapper was missing `transactionHash`.
Tested with: https://gist.github.cbhq.net/yuga-cohler/22701ee25995ce74da767e4f87442401
Output:
```
Created smart account: 0x6Cbe04340Dbe10BAf660a7C964538B9761e88FCC
User operation sent with operation hash:  0x39a3cd2476ee1a2da7888f4ca9da01905c123fd608aa7497a27a3018fb2b95b7
Waiting for user operation to be confirmed...
User operation confirmed with status:  complete
User operation:  {
network: 'base-sepolia',
userOpHash: '0x39a3cd2476ee1a2da7888f4ca9da01905c123fd608aa7497a27a3018fb2b95b7',
status: 'complete',
transactionHash: '0x88e8c5045bc9cbed47658a162b497ea6db9c1fac40414b7a1c3fa1a72ebfb2d5',
calls: [
{
to: '0x0499c34d5302bD4c8935F7b3A73bAd71876a0C5B',
value: 0n,
data: '0x'
}
]
}
User operation transaction hash: …
```

fix(typescript): return transactionHash in getUserOperation

---

typescript/.changeset/bright-bananas-move.md
typescript/CHANGELOG.md
typescript/package.json

chore: bump @coinbase/cdp-sdk to 1.1.2

---

go/.env.example
go/examples/example.go

chore(go): rename CDP_API_KEY_ID

---

README.md

this fixes the Contributors anchor in the README.md file!
| before | after |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e22f2f85-bed0-44b9-b212-cdeec01a4097) | ![image](https://github.com/user-attachments/assets/977ffbe8-ca33-44c9-b2b5-eb256da275ca) |
No tests needed!

fix: Fix contributors anchor

---

typescript/.changeset/short-onions-wear.md
typescript/.changeset/twelve-lemons-chew.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

Bumps `@coinbase/cdp-sdk` to v1.2.0

chore: bump @coinbase/cdp-sdk to 1.2.0

---

python/cdp/evm_client.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py

Specify and fix return types for EVM client in Python

bugfix: Specify return types for EVM client in Python

---

.github/workflows/typescript_e2e_test.yml
typescript/.changeset/shaggy-candles-sneeze.md
typescript/src/README.md
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/e2e.test.ts
typescript/src/examples/evm/sendManyTransactions.ts
typescript/src/examples/evm/sendTransaction.ts
typescript/src/examples/evm/sendTransactionWithViem.ts
typescript/src/types/misc.ts

Implements `sendTransaction` in EvmClient.
Tested via the new local examples, as well as a new e2e test.

feat(typescript): add sendTransaction

---

python/README.md
python/cdp/evm_client.py
python/cdp/examples/evm/send_transaction_with_web3.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py
python/changelog.d/58.feature.md

Implements `sendTransaction` stub in evm_client.
Also adds `sendTransaction` to EvmServerAccount interface, enabling this usage:
```python
account = await cdp.evm.create_account()
tx_hash = await account.send_transaction(
transaction_dict={
"to": "0x...",
"value": w3.to_wei(0.000001, "ether"),
...
},
network="base-sepolia",
)
```
Tested via the new local examples, as well as a new e2e test that tests both interfaces (cdp.evm.sendTransaction and account.sendTransaction)

feat(python): add sendTransaction

---

typescript/.changeset/clean-ideas-hug.md
typescript/.changeset/lucky-boxes-dress.md
typescript/.changeset/shaggy-candles-sneeze.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.3.0

---

README.md
python/README.md
typescript/src/README.md

Update README to include links to all docs

Update README to include links to all docs

---

typescript/src/README.md

chore: add faq to readme

---

typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.3.1

---

typescript/src/README.md

chore: update faq

---

examples/python/README.md
examples/typescript/README.md

chore: update example readmes

---

typescript/.changeset/thin-coins-burn.md
typescript/src/analytics.test.ts
typescript/src/analytics.ts
typescript/src/client/cdp.test.ts
typescript/src/client/cdp.ts
typescript/src/e2e.test.ts
typescript/src/index.ts

A circular dependency exists between `cdp.ts` and `analytics.ts` which Node.js is able to handle out-of-the-box, but Next.js is not. Next.js users encounter an error when importing the CDP-SDK, having to enable a config option in order to move past it. This is not ideal, so this PR breaks the circular dependency.
Tested that analytics events are still sent when the `DISABLE_CDP_ERROR_REPORTING` flag is off, and conversely they are not sent when the `DISABLE_CDP_ERROR_REPORTING` flag is on.

fix: remove circular dependency when importing analytics

---

typescript/.changeset/thin-coins-burn.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.3.2

---

python/cdp/__init__.py
python/cdp/analytics.py
python/cdp/cdp_client.py
python/cdp/test/test_analytics.py
python/changelog.d/82.bugfix.md

Python implementation of https://github.com/coinbase/cdp-sdk/pull/76
Updated automated tests, and tested manually locally

fix(python): remove circular dependency when importing analytics

---

RELEASE.md

chore: update release guide

---

.github/workflows/python_publish.yml

Fixes [the error](https://github.com/coinbase/cdp-sdk/actions/runs/14711478158/job/41284714109)
> Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip. This likely indicates that there are no dependencies to cache. Consider removing the cache step if it is not needed.
Caching is done at the uv level

chore: rm unused cache from python_publish

---

examples/python/evm/send_transaction.py
examples/python/uv.lock
python/README.md
python/cdp/__init__.py
python/cdp/evm_client.py
python/cdp/evm_transaction_types.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py
python/cdp/utils.py
python/changelog.d/86.feature.md

This PR is a fast follow to the addition of `send_transaction` in the Python SDK. It allows users to omit nonce and gas parameters, deferring to the Coinbase API to fill these in. If users with, they can still pass these parameters themselves. Users can also use [DynamicFeeTransaction from eth-account](https://eth-account.readthedocs.io/en/stable/eth_account.typed_transactions.html#module-eth_account.typed_transactions.dynamic_fee_transaction)
Added e2e for the scenarios:
* without nonce or gas params
* with nonce and gas params
* with `DynamicFeeTransaction` from `eth-account`
Also updated the relevant example

fix(python): support managed nonce and gas params in send transaction

---

typescript/.changeset/fifty-knives-lay.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.4.0

---

python/cdp/test/test_e2e.py

chore: use precreated test account in python e2e

---

examples/typescript/evm/account.transfer.ts
examples/typescript/evm/smartAccount.transfer.ts
typescript/.changeset/bumpy-tires-double.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/accounts/types.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts
typescript/src/actions/evm/transfer/transfer.test.ts
typescript/src/actions/evm/transfer/transfer.ts
typescript/src/actions/evm/transfer/types.ts
typescript/src/actions/evm/transfer/utils.ts
typescript/src/actions/evm/types.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/e2e.test.ts
typescript/src/utils/serializeTransaction.ts

This PR adds a `.transfer` method to EvmAccount and EvmSmartAccount.
Added e2e tests and examples

feat(typescript): add transfer method to EvmAccount and EvmSmartAccount

---

typescript/.changeset/bumpy-tires-double.md
typescript/.changeset/slow-meals-knock.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.5.0

---

examples/python/evm/account.transfer.py
examples/python/evm/smartAccount.transfer.py
examples/python/uv.lock
python/Makefile
python/README.md
python/cdp/__init__.py
python/cdp/actions/evm/transfer/__init__.py
python/cdp/actions/evm/transfer/account_transfer_strategy.py
python/cdp/actions/evm/transfer/constants.py
python/cdp/actions/evm/transfer/smart_account_transfer_strategy.py
python/cdp/actions/evm/transfer/transfer.py
python/cdp/actions/evm/transfer/types.py
python/cdp/actions/evm/transfer/utils.py
python/cdp/evm_client.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/test/test_account_transfer_strategy.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_server_account.py
python/changelog.d/95.feature.md

feat(python): add transfer method to EvmAccount and EvmSmartAccount

---

examples/python/evm/get_or_create_account.py
examples/python/solana/get_or_create_account.py
python/README.md
python/cdp/evm_client.py
python/cdp/solana_client.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py
python/cdp/test/test_solana_client.py
python/changelog.d/98.feature.md

Add `get_or_create_account` functions to both the evm and solana python sdks to combine the account existence check with conditional account creation, for faster and better devx.
Added unit tests and examples

feat(python): Add get_or_create_account for evm and solana

---

examples/typescript/evm/account.listTokenBalances.ts
examples/typescript/evm/account.requestFaucet.ts
examples/typescript/evm/account.sendTransaction.ts
examples/typescript/evm/smartAccount.listTokenBalances.ts
examples/typescript/evm/smartAccount.sendUserOperation.ts
examples/typescript/evm/smartAccount.waitForUserOperation.ts
typescript/.changeset/bitter-pillows-sell.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/accounts/types.ts
typescript/src/actions/evm/listTokenBalances.ts
typescript/src/actions/evm/requestFaucet.ts
typescript/src/actions/evm/sendTransaction.ts
typescript/src/actions/evm/sendUserOperation.test.ts
typescript/src/actions/evm/sendUserOperation.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts
typescript/src/actions/evm/types.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/e2e.test.ts

Adds actions on EvmAccount and EvmSmartAccount, enabling experiences like:
```ts
const account = await cdp.evm.createAccount();
account.requestFaucet(...);
accound.sendTransaction(...);
```
This is scoped to EVM accounts, Solana is deferred.
Added e2e tests and ran each new example script manually.

feat(typescript): add actions to EvmAccount and EvmSmartAccount

---

.github/workflows/typescript_publish.yml

Fixes https://github.com/coinbase/cdp-sdk/actions/runs/14863259609
> The workflow is not valid. .github/workflows/typescript_publish.yml (Line: 58, Col: 3): Error calling workflow 'coinbase/cdp-sdk/.github/workflows/deploy-gh-pages.yml@b787854c0f78f12af071f3ad429d59b79845dec1'. The workflow is requesting 'actions: read, pages: write', but is only allowed 'actions: none, pages: none'.

chore: pass permission to deploy docs

---

.github/workflows/typescript_publish.yml

chore: add missing permissions

---

.github/workflows/typescript_publish.yml

chore: add cwd to changesets action

---

examples/typescript/evm/account.transfer.ts
examples/typescript/evm/smartAccount.transfer.ts
typescript/.changeset/little-maps-talk.md
typescript/src/README.md
typescript/src/accounts/types.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts
typescript/src/actions/evm/transfer/transfer.test.ts
typescript/src/actions/evm/transfer/transfer.ts
typescript/src/actions/evm/transfer/types.ts
typescript/src/actions/evm/types.ts
typescript/src/client/evm/evm.types.ts

This PR adds some missing options to the transfer methods:
* For SmartAccount: paymasterUrl and waitOptions (mapping from UserOperation WaitOptions)
* For Account: waitOptions (mapping from viem's waitForTransactionReceipt)
Added unit tests

feat(typescript): add wait options and paymaster url to transfer method

---

.github/workflows/update_openapi.yml

chore: update permissions for openapi updater

---

examples/python/solana/get_account.py
examples/python/solana/send_batch_transaction.py
examples/python/solana/send_transaction.py
examples/python/uv.lock
examples/typescript/solana/signAndSendBatchTransaction.ts
examples/typescript/solana/signAndSendTransaction.ts
examples/typescript/solana/signAndSendVersionedTransaction.ts

Add examples for Solana batch transactions

Add examples for Solana batch transactions

---

.github/workflows/python_e2e_test.yml
.github/workflows/typescript_e2e_test.yml
python/cdp/test/test_e2e.py
typescript/.env.example
typescript/CONTRIBUTING.md
typescript/package.json
typescript/src/e2e.test.ts

Adds eth balance check to e2e tests

chore(typescript): improve e2e setup

---

examples/typescript/evm/smartAccount.getUserOperation.ts
typescript/.changeset/calm-ads-look.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/actions/evm/getUserOperation.ts
typescript/src/actions/evm/types.ts
typescript/src/client/evm/evm.ts
typescript/src/e2e.test.ts

Add `getUserOperation` to EVM smart accounts. This makes it so that, instead of
```ts
await cdp.evm.getUserOperation({
smartAccount,
userOpHash,
});
```
users can now directly call the function from the smart account like so:
```ts
await smartAccount.getUserOperation({
userOpHash,
});
```
Added unit and e2e tests. Also added an example for the smart account action.

feat(typescript): Add get user operation for evm smart account

---

python/cdp/test/test_e2e.py
typescript/src/e2e.test.ts

chore: fix e2e

---

examples/typescript/evm/sendTransaction.ts

The logs currently make it seem like the tx worked, even while it is still being confirmed (and potentially timing out)

chore: update evm/sendTransaction.ts

---

examples/python/evm/account.list_token_balances.py
examples/python/evm/account.request_faucet.py
examples/python/evm/account.send_transaction.py
examples/python/evm/smart_account.get_user_operation.py
examples/python/evm/smart_account.list_token_balances.py
examples/python/evm/smart_account.request_faucet.py
examples/python/evm/smart_account.send_user_operation.py
examples/python/evm/smart_account.wait_for_user_operation.py
python/README.md
python/cdp/actions/evm/list_token_balances.py
python/cdp/actions/evm/request_faucet.py
python/cdp/actions/evm/send_transaction.py
python/cdp/actions/evm/send_user_operation.py
python/cdp/actions/evm/transfer/smart_account_transfer_strategy.py
python/cdp/evm_client.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/test/actions/evm/test_send_user_operation.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_client.py
python/cdp/test/test_evm_server_account.py
python/cdp/test/test_evm_smart_account.py
python/changelog.d/114.feature.md

This is the python counterpart to https://github.com/coinbase/cdp-sdk/pull/99.
It adds account actions to evm server and smart accounts.
It also includes `get_user_operation` on the evm smart account, which has not yet been added to the typescript sdk.
```py
account = await cdp.evm.get_or_create_account(name="MyAccount");
account.request_faucet(...);
accound.send_transaction(...);
```
Solana account actions will be added later.
Added unit and e2e tests. Also added examples.

feat(python): Add account actions to evm server and smart accounts

---

examples/typescript/solana/account.requestFaucet.ts
examples/typescript/solana/account.signMessage.ts
examples/typescript/solana/account.signTransaction.ts
typescript/.changeset/chilly-signs-go.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/accounts/evm/types.ts
typescript/src/accounts/solana/toSolanaAccount.ts
typescript/src/accounts/solana/types.ts
typescript/src/actions/evm/sendUserOperation.test.ts
typescript/src/actions/evm/sendUserOperation.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts
typescript/src/actions/evm/transfer/transfer.ts
typescript/src/actions/evm/transfer/types.ts
typescript/src/actions/solana/requestFaucet.ts
typescript/src/actions/solana/signMessage.ts
typescript/src/actions/solana/signTransaction.ts
typescript/src/actions/solana/types.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.types.ts
typescript/src/client/solana/solana.test.ts
typescript/src/client/solana/solana.ts
typescript/src/client/solana/solana.types.ts
typescript/src/e2e.test.ts
typescript/src/index.ts

Add `requestFaucet`, `signMessage`, and `signTransaction` to solana accounts. This makes it that we can call these functions straight from the Solana accounts instead of the Solana client.
For example:
```ts
const account = await cdp.solana.createAccount();
const { signature } = await account.signMessage({
message: "Hello, world!"
});
```
This PR introduces a new type `SolanaAccount` which is a union type of the base `Account` Solana type and `AccountActions` for Solana. The impact here is that`getAccount`, `createAccount`, and `listAccounts` now return this type, so that the actions may be called directly from the account responses.
Added unit tests and examples.

feat(typescript) Add solana actions

---

examples/python/evm/account.transfer.py
examples/python/evm/smart_account.transfer.py
python/README.md
python/cdp/__init__.py
python/cdp/actions/evm/transfer/__init__.py
python/cdp/actions/evm/transfer/account_transfer_strategy.py
python/cdp/actions/evm/transfer/smart_account_transfer_strategy.py
python/cdp/actions/evm/transfer/transfer.py
python/cdp/actions/evm/transfer/types.py
python/cdp/test/test_account_transfer_strategy.py
python/changelog.d/105.feature.md

This PR adds some missing options to the transfer methods:
* For SmartAccount: paymaster_url and wait_options (mapping from UserOperation WaitOptions)
* For Account: wait_options (mapping from web3's waitForTransactionReceipt)
Added unit tests, tested manually with paymaster_url and wait_options

feat(python): add wait options and paymaster url to transfer method

---

typescript/.changeset/calm-ads-look.md
typescript/.changeset/chilly-signs-go.md
typescript/.changeset/little-maps-talk.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.7.0

---

examples/python/solana/account.request_faucet.py
examples/python/solana/account.sign_message.py
examples/python/solana/account.sign_transaction.py
python/README.md
python/cdp/actions/solana/request_faucet.py
python/cdp/actions/solana/sign_message.py
python/cdp/actions/solana/sign_transaction.py
python/cdp/solana_account.py
python/cdp/solana_client.py
python/cdp/test/actions/solana/test_request_faucet.py
python/cdp/test/actions/solana/test_sign_message.py
python/cdp/test/actions/solana/test_sign_transaction.py
python/cdp/test/test_e2e.py
python/cdp/test/test_solana_account.py
python/cdp/test/test_solana_client.py
python/changelog.d/135.feature.md

Adds SolanaAccount convenience class to call Actions directly on a returned Account. This sets us up to add a `transfer` helper method on to the SolanaAccount
Added unit tests, e2e and examples

feat(python): add solana account

---

examples/typescript/evm/account.signTypedData.ts
examples/typescript/evm/signTypedData.ts
typescript/.changeset/rare-bars-refuse.md
typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/types.ts
typescript/src/actions/evm/transfer/types.ts
typescript/src/client/evm/evm.test.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/e2e.test.ts
typescript/src/types/misc.ts

With this PR, the cdp client and server accounts may now sign EIP-712 typed data.
For example:
```ts
const signature = await cdp.evm.signTypedData({
address: account.address,
message: <eip-712-message>
});
```
or
```ts
const signature = await account.signTypedData({
message: <eip-712-message>
});
```
Added examples and unit tests.

feat(typescript) Add support for EIP-712 signing

---

typescript/src/analytics.test.ts
typescript/src/analytics.ts
typescript/src/client/cdp.ts
typescript/src/client/evm/evm.ts
typescript/src/client/solana/solana.ts
typescript/src/e2e.test.ts

* Adds error tracking to account actions
* Filters out APIErrors
Tested manually

chore(typescript): improve analytics

---

python/cdp/analytics.py
python/cdp/cdp_client.py
python/cdp/evm_client.py
python/cdp/solana_client.py
python/cdp/test/test_analytics.py

* Adds error tracking to account actions
* Filters out APIErrors

chore(python): improve analytics

---

typescript/.changeset/open-cameras-cheer.md
typescript/.changeset/quiet-bushes-cough.md
typescript/.changeset/rare-bars-refuse.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.8.0

---

examples/typescript/solana/account.transfer.ts
typescript/.changeset/bright-groups-study.md
typescript/pnpm-lock.yaml
typescript/src/README.md
typescript/src/accounts/solana/toSolanaAccount.ts
typescript/src/actions/solana/constants.ts
typescript/src/actions/solana/transfer.test.ts
typescript/src/actions/solana/transfer.ts
typescript/src/actions/solana/types.ts
typescript/src/actions/solana/utils.test.ts
typescript/src/actions/solana/utils.ts
typescript/src/client/solana/solana.test.ts
typescript/src/e2e.test.ts
typescript/src/package.json

This PR adds a Transfer method to the Solana account, abstracting away the complexity of creating Solana transactions. It supports native SOL transfer as well as SPL token transfers. The method returns the transaction signature, which can then be used to wait for confirmation.
Added unit & e2e tests, and tested locally with the new example.
Result of running `pnpm tsx solana/account.transfer.ts`:
```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Balance too low, requesting SOL from faucet...
Waiting for funds...
Waiting for funds...
Waiting for funds...
Waiting for funds...
Waiting for funds...
Waiting for funds...
Waiting for funds...
Account funded with 0.00375 SOL
Sent transaction with signature: …
```

feat(typescript): add transfer to solana account

---

examples/python/evm/account.transfer.py
examples/python/evm/smart_account.transfer.py
python/README.md
python/cdp/__init__.py
python/cdp/actions/evm/transfer/__init__.py
python/cdp/actions/evm/transfer/account_transfer_strategy.py
python/cdp/actions/evm/transfer/smart_account_transfer_strategy.py
python/cdp/actions/evm/transfer/transfer.py
python/cdp/actions/evm/transfer/types.py
python/cdp/actions/evm/transfer/utils.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/test/test_account_transfer_strategy.py
python/cdp/test/test_e2e.py
python/cdp/test/test_parse_units.py
python/cdp/utils.py
python/changelog.d/137.feature.md

This PR makes several changes to the EVM Transfer API and implementation to bring the DevX in line with what developers expect. The changes to the API are:
1. Split out built-in transaction receipt waiting
2. Accept only atomic value for `amount`
These changes make the implementation simpler, as the SDK no longer manages the waiting, and the SDK doesn't have to parse units to arrive at an atomic `amount`. The example scripts, readme and e2e have been updated to reflect the new behavior.
Result of running `uv run python evm/account.transfer.ts`:
```
Requesting USDC and ETH from faucet...
Sending 0.01 USDC from 0x9cCB99345B59101c7E9A6E2688CaFF7b10664488 to 0xBEEb6885678f3078AFEE24A39994fD7208113a9e...
Transfer status: 1
Explorer link: …
```

feat(python): update evm transfer api

---

.github/workflows/python_e2e_test.yml
.github/workflows/typescript_e2e_test.yml
examples/typescript/evm/account.transfer.ts
examples/typescript/evm/smartAccount.transfer.ts
python/cdp/test/test_e2e.py
typescript/.changeset/icy-moons-mate.md
typescript/src/README.md
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/accountTransferStrategy.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.test.ts
typescript/src/actions/evm/transfer/smartAccountTransferStrategy.ts
typescript/src/actions/evm/transfer/transfer.test.ts
typescript/src/actions/evm/transfer/transfer.ts
typescript/src/actions/evm/transfer/types.ts
typescript/src/actions/evm/transfer/utils.ts
typescript/src/actions/evm/types.ts
typescript/src/e2e.test.ts

This PR makes several changes to the EVM Transfer API and implementation to bring the DevX in line with what developers expect. The changes to the API are:
1. Split out built-in transaction receipt waiting
2. Accept only `bigint` `amount`
These changes make the implementation simpler, as the SDK no longer manages the waiting, and the SDK doesn't have to parse units to arrive at a `bigint` `amount`. The example scripts, readme and e2e have been updated to reflect the new behavior.
Result of running `pnpm tsx evm/account.transfer.ts`:
```
Requesting USDC and ETH from faucet...
Received USDC from faucet. Explorer link: https://sepolia.basescan.org/tx/0xae9349cbc79b84da5e53d34f565e5ebbb62ab5f79fa02575e8eb7706cb4af5b0
Received ETH from faucet. Explorer link: …
```

feat(typescript): update evm transfer api

---

python/cdp/analytics.py
typescript/src/analytics.ts

chore: include sdk version in analytics event

---

typescript/.changeset/bright-groups-study.md
typescript/.changeset/icy-moons-mate.md
typescript/.changeset/ready-lights-cut.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.9.0

---

typescript/.changeset/upset-peas-scream.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.10.0

---

typescript/src/accounts/evm/types.ts
typescript/src/types/misc.ts

chore: use hex in eip712 types

---

examples/python/uv.lock
python/cdp/evm_client.py
python/cdp/test/test_e2e.py
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/e2e.test.ts

This makes it possible for us to run tests with different public keys. This is not intended to be used by end users.

chore: add optional parameter to receive an encryption public key

---

python/cdp/openapi_client/cdp_api_client.py
python/changelog.d/192.bugfix.md

Log response body in the `errorMessage` for unexpected non-OAPI error scenarios.
Before:
```
statusCode: 400,
errorType: 'unexpected_error',
errorMessage: 'An unexpected error occurred.',
correlationId: undefined,
errorLink: 'https://docs.cdp.coinbase.com/api-v2/docs/errors',
[cause]: undefined
```
After:
```
statusCode: 400,
errorType: 'unexpected_error',
errorMessage: 'An unexpected error occurred: "<html>\\r\\n<head><title>400 Request Header Or Cookie Too Large</title></head>\\r\\n<body>\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<center>Request Header Or Cookie Too Large</center>\\r\\n</body>\\r\\n</html>\\r\\n"',
correlationId: undefined,
errorLink: 'https://docs.cdp.coinbase.com/api-v2/docs/errors',
[cause]: undefined
```
A couple of things to include in your PR for …

fix(python): Log response body for unexpected non-OAPI error scenarios

---

typescript/.changeset/breezy-ads-play.md
typescript/.changeset/polite-owls-ask.md
typescript/.changeset/six-moons-begin.md
typescript/.changeset/sweet-aliens-sin.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.14.0

---

typescript/.changeset/afraid-wasps-raise.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.15.0

---

typescript/src/accounts/evm/toNetworkScopedEvmSmartAccount.test.ts
typescript/src/accounts/evm/toNetworkScopedEvmSmartAccount.ts
typescript/src/accounts/evm/types.ts

Scaffolds toNetworkScopedEvmSmartAccount to be used to hoist network and manage Node connections
~- [ ] Updated the [typescript README](https://github.com/coinbase/cdp-sdk/blob/main/typescript/src/README.md) if relevant~
~- [ ] Updated the [python README](https://github.com/coinbase/cdp-sdk/blob/main/python/README.md) if relevant~
~- [ ] Added a changelog entry~

feat: add toNetworkScopedEvmSmartAccount

---

typescript/src/accounts/evm/toEvmServerAccount.test.ts
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.test.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/accounts/evm/types.ts
typescript/src/client/evm/evm.types.ts

Adds basic useNetwork function (marked experimental)
~- [ ] Updated the [typescript README](https://github.com/coinbase/cdp-sdk/blob/main/typescript/src/README.md) if relevant~
~- [ ] Updated the [python README](https://github.com/coinbase/cdp-sdk/blob/main/python/README.md) if relevant~
~- [ ] Added a changelog entry~

feat: scaffold experimental useNetwork function

---

typescript/.changeset/calm-impalas-rule.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.18.0

---

examples/typescript/evm/baseAccount.sendTransaction.ts
typescript/.changeset/many-pandas-teach.md
typescript/src/accounts/evm/resolveViemClients.ts
typescript/src/e2e.test.ts
typescript/src/openapi-client/cdpApiClient.ts

This PR adds a fetch call to lookup the users Base Node URL and use that in their managed viem PublicClient. This works for Base mainnet and Base Sepolia. Example usage:
```ts
const account = await cdp.evm.getOrCreateAccount({ name: "MyAccount" });
const baseAccount = await account.useNetwork("base-sepolia");
const txResult = await baseAccount.sendTransaction({
transaction: {
to: "0x4252e0c9A3da5A2700e7d91cb50aEf522D0C6Fe8",
value: parseEther("0.000001"),
},
});
// Uses Base Node RPC under the hood!
const receipt = await baseAccount.waitForTransactionReceipt({
hash: txResult.transactionHash,
});
```
Added an e2e test that spies on the network calls going out and asserts that a call is made to the expected RPC endpoint.

feat: add base node url lookup

---

typescript/src/e2e.test.ts

chore: skip base node test in local env

---

python/cdp/auth/utils/jwt.py
python/cdp/utils.py
python/changelog.d/212.bugfix.md

Include the hash the key-sorted json of the request body in the wallet jwt claims, instead of the larger request body json, to avoid errors where request header size is too large.
The backend also comes with changes to handle this update.
Locally running example scripts with different hardcoded request bodies to test different scenarios.

chore(python): Hash req body in wallet jwt claims

---

typescript/.changeset/six-houses-send.md
typescript/src/e2e.test.ts

This PR includes handling for the RSA Public Key used for Import Solana Account. Currently, Dev E2E tests are failing because they are using the incorrect RSA Public Key. 
This PR checks if there are any environment variables for the RSA public key based on the environment, and uses them instead of the default prod RSA public key.

fix: use env var for RSA public key

---

typescript/.changeset/cuddly-hats-exist.md
typescript/.changeset/hungry-ravens-reply.md
typescript/.changeset/large-swans-repair.md
typescript/.changeset/short-states-change.md
typescript/.changeset/six-houses-send.md
typescript/.changeset/spicy-singers-decide.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.21.0

---

typescript/.changeset/khaki-shirts-count.md
typescript/src/client/cdp.test.ts
typescript/src/client/cdp.ts

Because of our dependency on the `crypto` library, we depend on Node.js >v19.

chore(typescript): add check to ensure minimum nodejs version

---

typescript/.changeset/khaki-shirts-count.md
typescript/.changeset/wicked-areas-cut.md
typescript/.changeset/wide-boats-punch.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.22.0

---

examples/python/policies/sign_typed_data_policy.py
examples/typescript/policies/signTypedDataPolicy.ts
python/cdp/policies/request_transformer.py
python/cdp/policies/response_transformer.py
python/cdp/policies/types.py
python/changelog.d/264.feature.md
typescript/.changeset/gentle-plants-laugh.md
typescript/src/policies/schema.ts

This PR adds SignTypedData Policy support in the Python and TypeScript SDKs. A basic example is included and was used to test the policy evaluation.
Running the TS example:
```
Created permit policy. Policy ID: ca803617-5f10-4b15-bc7c-abb85a109dc5
Signature: 0x3576ec196d83eecbacb23358d56f638e29e97c7b5015aca463ff842755b63a6c5f1380564b36a30286a871dbc3d9c862f15030d77e434040950bf819502c014c1b
Error: APIError: The request is forbidden due to violating at least one configured policy.
at cdpApiClient (/Users/ryan/code/public/cdp-sdk/typescript/src/openapi-client/cdpApiClient.ts:148:15)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async Object.signTypedData (/Users/ryan/code/public/cdp-sdk/typescript/src/accounts/evm/toEvmServerAccount.ts:111:22)
at async …
```

feat: add support for policy creation on signTypedData

---

typescript/.changeset/gentle-plants-laugh.md
typescript/.changeset/tricky-memes-taste.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.23.0

---

typescript/.changeset/cold-zoos-wave.md
typescript/src/actions/evm/getUserOperation.test.ts
typescript/src/actions/evm/getUserOperation.ts
typescript/src/client/evm/evm.types.ts

fix: add ability to pass address in evm.getUserOperation

---

typescript/.changeset/cold-zoos-wave.md
typescript/.changeset/salty-toys-start.md
typescript/.changeset/short-views-say.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.24.0

---

.cursor/rules/repository-structure.mdc
CLAUDE.md
go/.cursor/rules/go-development.mdc
python/.cursor/rules/python-development.mdc
typescript/.cursor/rules/typescript-development.mdc

Adds Claude and Cursor rules for better AI development 🤖 

chore: add ai rules

---

typescript/.changeset/easy-worlds-knock.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.25.0

---

examples/python/evm/transfer.py
examples/typescript/evm/baseAccount.transfer.ts

Add examples for EVM transfer function. Didn't add this with the transfer function PR itself.

chore: Add examples for EVM transfer function

---

typescript/.changeset/gold-books-pay.md
typescript/.changeset/poor-rabbits-relate.md
typescript/.changeset/soft-colts-fetch.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.26.0

---

python/cdp/actions/evm/swap/types.py
python/cdp/analytics.py
python/cdp/auth/utils/jwt.py
python/cdp/errors.py
python/cdp/evm_client.py
python/cdp/evm_local_account.py
python/cdp/policies/types.py
python/cdp/solana_client.py

This PR adds a UserInputValidationError which is filtered out at the analytics layer so that we do not send these types of errors to Amplitude.
Tested manually

chore(python): do not emit user input validation errors

---

typescript/src/README.md
typescript/src/accounts/evm/toEvmServerAccount.ts
typescript/src/accounts/evm/toEvmSmartAccount.ts
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.ts
typescript/src/accounts/evm/toNetworkScopedEvmSmartAccount.ts
typescript/src/accounts/solana/toSolanaAccount.ts
typescript/src/analytics.ts
typescript/src/client/cdp.ts
typescript/src/client/evm/evm.ts
typescript/src/client/policies/policies.ts
typescript/src/client/solana/solana.ts

Adds usage analytics to capture which account actions are being called, and with which network (where relevant). Builders can opt-out of usage tracking by setting the environment variable `DISABLE_CDP_USAGE_TRACKING=true`.
Tested manually by running some example scripts and checking the events flowing through the system. Also tested disabling the tracking with `DISABLE_CDP_USAGE_TRACKING`.

chore(typescript): add usage analytics

---

python/README.md
python/cdp/analytics.py
python/cdp/cdp_client.py
python/cdp/evm_client.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/policies_client.py
python/cdp/solana_account.py
python/cdp/solana_client.py
python/cdp/test/test_analytics.py

Adds usage analytics to capture which account actions are being called, and with which network (where relevant). Builders can opt-out of usage tracking by setting the environment variable `DISABLE_CDP_USAGE_TRACKING=true`.
Tested manually by running some example scripts and checking the events flowing through the system. Also tested disabling the tracking with `DISABLE_CDP_USAGE_TRACKING`.

chore(python): add usage analytics

---

typescript/.changeset/pretty-times-tap.md
typescript/.changeset/quick-ideas-agree.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

Bumping coinbase/cdp-sdk version to `v1.27.0`

chore: bump @coinbase/cdp-sdk to 1.27.0

---

typescript/.changeset/odd-llamas-yawn.md
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.test.ts
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.ts

This PR fixes an issue where managed mode methods were not available when using a custom RPC.
This was tested with the `evm/scopedAccount.customNode.ts` script.

fix: fix managed mode methods not being available with custom rpc

---

python/cdp/test/test_e2e.py
typescript/src/e2e.test.ts

chore: Update e2e tests to be more robust for sendTransaction on Solana

---

examples/python/solana/account.transfer.py
examples/python/uv.lock
examples/typescript/solana/account.transfer.ts
python/cdp/actions/solana/transfer.py
python/cdp/actions/solana/utils.py
python/cdp/test/test_e2e.py
python/changelog.d/309.bugfix.md
typescript/.changeset/giant-cycles-take.md
typescript/src/actions/solana/transfer.test.ts
typescript/src/actions/solana/transfer.ts
typescript/src/actions/solana/utils.test.ts
typescript/src/actions/solana/utils.ts

Use our new send transaction api for solana for `account.transfer`.
Updated unit tests. Ran examples successfully.
Python
```bash
❯uv run python solana/account.transfer.py
Sent transaction with signature: 36853kBmtxYof6cXVEyU4qdtbxCnH5rCbScBrsempxiaWrKi6wbkJah6zVESfePKAdxUcpHProHW45fGSmg4G3s8. Waiting for confirmation...
Transaction confirmed! Link: https://explorer.solana.com/tx/36853kBmtxYof6cXVEyU4qdtbxCnH5rCbScBrsempxiaWrKi6wbkJah6zVESfePKAdxUcpHProHW45fGSmg4G3s8?cluster=devnet
```
TypeScript
```bash
❯ pnpm tsx solana/account.transfer.ts
Sent transaction with signature: 3ipf5SJYWzLJxW4EjXT84LaewL5728aWKcSNiNWsns64LpticZrRhofZQxbXV3k4i91m2ygbHEgyKAqbwGtp68Wg. Waiting for confirmation...
Transaction confirmed: Link: https://explorer.solana.com/tx/3ipf5SJYWzLJxW4EjXT84LaewL5728aWKcSNiNWsn …
```

chore: Use CDP SendSolanaTransaction API for transfer action

---

python/cdp/test/test_e2e.py

chore: skip flaky python test

---

typescript/src/e2e.test.ts

This test itself is not flaky, but it causes flakiness in other tests that run concurrently and end up failing due to violating the policy set up by this test.

chore: skip flaky policy test

---

typescript/.changeset/small-bottles-rhyme.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.29.0

---

typescript/src/client/evm/evm.types.ts

chore: add spend permission flag on getOrCreateSmartAccount

---

python/cdp/policies/request_transformer.py
python/cdp/policies/response_transformer.py
python/cdp/policies/types.py
python/cdp/test/test_e2e.py
python/changelog.d/317.bugfix.md

fix(python): add evmData to types

---

python/cdp/test/test_e2e.py

chore: skip python list policies test again :(

---

examples/python/evm/scoped_account.send_transaction.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/network_capabilities.py
python/cdp/network_scoped_evm_server_account.py
python/cdp/network_scoped_evm_smart_account.py
python/cdp/test/test_e2e.py
python/cdp/test/test_evm_server_account.py

Python users can scope EVM accounts and EVM Smart Accounts to a network or RPC URL
Base or base-sepolia tx sends use the users base(-sepolia) node

feat: Add Managed Mode Feature to Python SDK

---

python/cdp/test/test_e2e.py

chore: Skip flaky test for now

---

python/cdp/test/test_e2e.py
typescript/src/accounts/evm/toNetworkScopedEvmServerAccount.ts
typescript/src/accounts/evm/toNetworkScopedEvmSmartAccount.ts
typescript/src/client/evm/evm.ts
typescript/src/client/solana/solana.ts

This PR does two things:
* For actions calls from managed mode accounts, include a property to denote that the action call is on a managed account
* Stop double counting get(Smart)Account and/or create(Smart)Account when called from getOrCreate(Smart)Account

chore: analytics tweaks

---

typescript/.changeset/polite-bottles-tap.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.31.1

---

typescript/.changeset/tidy-news-care.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.32.0

---

typescript/.changeset/lazy-vans-move.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

Releases `netUSDChange` criteria https://github.com/coinbase/cdp-sdk/pull/355

chore: bump @coinbase/cdp-sdk to 1.33.0

---

.github/workflows/typescript_publish.yml

Revert "chore: use trusted publishing"

---

examples/typescript/evm/createSpendPermission.ts
examples/typescript/evm/revokeSpendPermission.ts
examples/typescript/evm/smartAccount.useSpendPermission.ts
examples/typescript/evm/spender.listSpendPermissions.ts
typescript/src/actions/evm/spend-permissions/account.use.ts
typescript/src/actions/evm/spend-permissions/resolveSpendPermission.ts
typescript/src/actions/evm/spend-permissions/smartAccount.use.ts
typescript/src/actions/evm/spend-permissions/types.ts
typescript/src/client/evm/evm.ts
typescript/src/client/evm/evm.types.ts
typescript/src/index.ts
typescript/src/spend-permissions/utils.test.ts
typescript/src/spend-permissions/utils.ts

This PR does a couple things on the TypeScript side to improve the DevX of creating Spend Permissions:
1. Allows devs to pass in human-readable strings for the token (e.g. `eth` or `usdc`).
2. Allows devs to omit `salt` and `extraData`, which will fallback to `0n` and `0x` respectively.
I ran all examples manually to ensure they continue to work.

feat: improve spend permission create devx

---

examples/python/evm/create_spend_permission.py
examples/python/evm/list_spend_permissions.py
examples/python/evm/revoke_spend_permission.py
examples/python/evm/smart_account.use_spend_permission.py
examples/python/uv.lock
python/cdp/__init__.py
python/cdp/actions/evm/spend_permissions/account_use.py
python/cdp/actions/evm/spend_permissions/smart_account_use.py
python/cdp/evm_client.py
python/cdp/evm_server_account.py
python/cdp/evm_smart_account.py
python/cdp/spend_permissions/__init__.py
python/cdp/spend_permissions/types.py
python/cdp/spend_permissions/utils.py
python/cdp/test/spend_permissions/test_utils.py

Python variant of #360 
Tested by manually running all spend permissions examples.

feat(python): improve spend permission create devx

---

examples/python/evm/account.use_spend_permission.py
examples/python/evm/create_spend_permission.py
examples/python/evm/list_spend_permissions.py
examples/python/evm/revoke_spend_permission.py
examples/python/evm/smart_account.use_spend_permission.py
python/cdp/actions/evm/spend_permissions/account_use.py
python/cdp/actions/evm/spend_permissions/smart_account_use.py
python/cdp/spend_permissions/types.py
python/cdp/spend_permissions/utils.py
python/cdp/test/actions/evm/spend_permissions/test_account_use.py
python/cdp/test/actions/evm/spend_permissions/test_smart_account_use.py
python/cdp/test/spend_permissions/test_utils.py
python/cdp/test/test_evm_client.py
python/changelog.d/370.bugfix.md

This PR is the Python variant of #367. See that PR for more context!
Ran all updated examples manually and verified output.

fix(python): implement additional feedback on create spend permission

---

typescript/.changeset/little-terms-divide.md
typescript/.changeset/rare-times-relax.md
typescript/.changeset/rude-ways-shake.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.34.0

---

python/cdp/network_scoped_evm_server_account.py

Instead of 
```
start = time()
while True:
try:
receipt = web3.eth.get_transaction_receipt(transaction_hash)
if receipt:
return dict(receipt)
except TransactionNotFound:
pass
if time() - start > timeout_seconds:
raise TimeoutError("Timeout waiting for transaction receipt.")
await asyncio.sleep(interval_seconds)
```
Replace it with 
`web3.eth.wait_for_transaction_receipt`

Replace polling with wait_for_transaction_receipt

---

examples/python/end_user/validate_access_token.py
examples/typescript/end-users/validateAccessToken.ts
python/README.md
python/cdp/api_clients.py
python/cdp/cdp_client.py
python/cdp/end_user_client.py
python/cdp/test/factories/end_user_factory.py
python/cdp/test/test_end_user_client.py
python/changelog.d/389.feature.md

- Adds new end user client to wrap the validate access token method, similar to typescript
- Fixes a typescript example
Note: depends on deployment in order to fix pydantic validation failures
- Unit tests
- Manual testing against dev

feat(CDPSDK-1409): validate access token method for python sdk

---

python/README.md
python/cdp/policies/request_transformer.py
python/cdp/policies/response_transformer.py
python/cdp/policies/types.py
python/cdp/test/test_e2e.py
python/cdp/test/test_policies_client.py
python/changelog.d/1446.feature.md
typescript/.changeset/warm-radios-ring.md
typescript/src/README.md
typescript/src/client/policies/policies.test.ts
typescript/src/policies/evmSchema.ts

- for ts policy zod schemas, create different evmNetwork criteria for prepareUserOperation and sendEvmTransaction rules
- implement sendUserOperation/prepareUserOperation in python (which were missing transformer functionality)
- fix broken readme links after docs update

chore(CDPSDK-1466): expand prepareUserOperation, sendEvmTransaction supported networks for evmNetwork

---

typescript/.changeset/curvy-candies-walk.md
typescript/.changeset/tasty-falcons-cheat.md
typescript/.changeset/warm-radios-ring.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.35.0

---

typescript/src/e2e.test.ts

The issue was 2-fold:
1. We recently introduced a way to randomize our policy test account for a given test run from a list of 10 accounts. See [here](https://github.com/coinbase/cdp-sdk/blob/main/typescript/src/e2e.test.ts#L1904). We did not fund these accounts.
2. SendTransaction on Solana now has a simulation step for optimization purposes to estimate the compute unit limit to set on the transaction.
The test were failing with `AccountNotFound` because the accounts had no funds. After funding, they were then failing with `InstructionError` and then because we were simulating on transfer amounts greater than the available account balances.
Solved by:
1. Manually funding all 10 aforementioned accounts with the faucet.
2. Reducing the policy criteria and transaction amounts so they are …

chore: Fix failing E2E sendSolTransaction policy evaluation tests

---

typescript/.changeset/rude-bikes-rhyme.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.37.0

---

typescript/package.json

chore: bump pnpm version

---

typescript/src/auth/utils/jwt.test.ts
typescript/src/auth/utils/jwt.ts

Only include reqHash in claims if request body is an object with at least one key that has a non-undefined value.
Added unit tests.

chore: Fix empty object hash in TS

---

typescript/.changeset/tidy-news-begin.md

Add changelog for TS empty object hash in x-wallet-auth header

---

typescript/.changeset/tidy-news-begin.md
typescript/src/CHANGELOG.md
typescript/src/package.json
typescript/src/version.ts

chore: bump @coinbase/cdp-sdk to 1.38.3

---

python/cdp/actions/evm/fund/fund.py
python/cdp/actions/evm/fund/quote_fund.py
python/cdp/actions/solana/fund/fund.py
python/cdp/actions/solana/fund/quote_fund.py
python/cdp/actions/wait_for_fund_operation_receipt.py
typescript/src/actions/evm/fund/fund.test.ts
typescript/src/actions/evm/fund/fund.ts
typescript/src/actions/evm/fund/quoteFund.test.ts
typescript/src/actions/evm/fund/quoteFund.ts
typescript/src/actions/solana/fund/fund.test.ts
typescript/src/actions/solana/fund/fund.ts
typescript/src/actions/solana/fund/quoteFund.test.ts
typescript/src/actions/solana/fund/quoteFund.ts
typescript/src/actions/waitForFundOperationReceipt.test.ts
typescript/src/actions/waitForFundOperationReceipt.ts

This supports the deprecation of the fund, quoteFund, and waitForFundOperationReceipt. The API endpoints have already been deprecated. This signifies the deprecation in the SDK.
NOTE: please do not merge this PR automatically. We want to ensure a smooth roll out for the deprecation. We want to inform the users of these methods before merging the deprecation of these methods.

fix(SPA-222): Removed deprecated onramp functions

---

python/cdp/test/test_e2e.py
typescript/src/e2e.test.ts

chore: bump e2e min required balance
